INSERT INTO regiones(id, nombre) VALUES (1, 'Norteamérica');
INSERT INTO regiones(id, nombre) VALUES (2, 'Sudamérica');
INSERT INTO regiones(id, nombre) VALUES (3, 'Europa');
INSERT INTO regiones(id, nombre) VALUES (4, 'Asia');
INSERT INTO regiones(id, nombre) VALUES (5, 'África');
INSERT INTO regiones(id, nombre) VALUES (6, 'Oceanía');
INSERT INTO regiones(id, nombre) VALUES (7, 'Medio Oriente');
INSERT INTO regiones(id, nombre) VALUES (8, 'Caribe');
INSERT INTO regiones(id, nombre) VALUES (9, 'América Central');
INSERT INTO regiones(id, nombre) VALUES (10, 'Antártida');

INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Samuel', 'Cano', 'samuel.cano@example.com', '2023-05-29', 1);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'John', 'Doe', 'john.doe@example.com', '2023-05-23', 1);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Jane', 'Smith', 'jane.smith@example.com', '2023-05-23', 2);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Michael', 'Johnson', 'michael.johnson@example.com', '2023-05-23', 3);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Emily', 'Brown', 'emily.brown@example.com', '2023-05-23', 4);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Daniel', 'Wilson', 'daniel.wilson@example.com', '2023-05-23', 5);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Olivia', 'Taylor', 'olivia.taylor@example.com', '2023-05-23', 6);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'William', 'Martinez', 'william.martinez@example.com', '2023-05-23', 7);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Sophia', 'Anderson', 'sophia.anderson@example.com', '2023-05-23', 8);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'James', 'Hernandez', 'james.hernandez@example.com', '2023-05-23', 9);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Emma', 'Garcia', 'emma.garcia@example.com', '2023-05-23', 10);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Alexander', 'Lopez', 'alexander.lopez@example.com', '2023-05-23', 1);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Mia', 'Perez', 'mia.perez@example.com', '2023-05-23', 2);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Benjamin', 'Ramirez', 'benjamin.ramirez@example.com', '2023-05-23', 3);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Ava', 'Gonzalez', 'ava.gonzalez@example.com', '2023-05-23', 4);
INSERT INTO clientes (id, nombre, apellido, email, create_at, region_id) VALUES (null, 'Sebastian', 'Torres', 'sebastian.torres@example.com', '2023-05-23', 5);